### ISSUE TITLE
Download data directly inside the notebook from S3 bucket

### ISSUE THREAD

**Issue by loicbachelot** [oceanhackweek/ohw21-proj-bioacoustics#10]
Using xarray to download data and open dataset directly from the notebook from http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/SOOP/SOOP-BA/ 

Here is a track but I couldn't get it to work yet, not sure what would be the path to the dataset
https://s3fs.readthedocs.io/en/latest/

**Comment by bgetraer** [comment]
Hi Loic! I think I may have resolved this issue. Check out the code at the beginning of [benjy_xarray_testing.ipynb](https://github.com/bgetraer/ohw21-proj-bioacoustics/blob/main/bioacoustics/data_exploration/benjy_xarray_testing.ipynb)

see if that works.

**Comment by loicbachelot** [comment]
Yes, that works! Great job thanks!
